name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudflare-stack-test"
database_id = "9b9c1088-cc08-4e5e-8c29-b493c0725eee"
migrations_dir = "./drizzle"
